### ISSUE TITLE
attempting to send a fraction of $ALF token crashes extension wallet

### ISSUE THREAD

**Issue by diomark** [alephium/extension-wallet#101]
Detail;s at https://discord.com/channels/747741246667227157/878206973781368842/1114624655156854785 - pasted here to make it easier.

Attempting to send a fraction of ALF (only alf, alph, ayin, test btc, others are fine) crashes the extension wallet with this error message
 ```
v0.7.1

{
  "stack": "Error: fractional component exceeds decimals [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT ] (fault=\"underflow\", operation=\"parseFixed\", code=NUMERIC_FAULT, version=bignumber/5.7.0)\n    at R.makeError (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:7:24588)\n    at R.throwError (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:7:24706)\n    at _ (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:7:90862)\n    at E (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:7:91873)\n    at Module.H (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:7:97430)\n    at Bo (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/502.js:1256:710)\n    at eC (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/502.js:1590:1801)\n    at ma (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2272:20863)\n    at Gr (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2274:3309)\n    at zu (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2274:47276)",
  "message": "fractional component exceeds decimals [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT ] (fault=\"underflow\", operation=\"parseFixed\", code=NUMERIC_FAULT, version=bignumber/5.7.0)",
  "reason": "fractional component exceeds decimals",
  "code": "NUMERIC_FAULT",
  "fault": "underflow",
  "operation": "parseFixed"
}

    at eC (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/502.js:1590:94)
    at div
    at t (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2723:7303)
    at Ct (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2723:7751)
    at chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2:26090
    at chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2701:3164
    at s1 (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/main.js:17:17234)
    at p (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2304:4460)
    at Ce (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2304:10014)
    at div
    at chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2:26090
    at chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2701:3164
    at chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2:26090
    at chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2701:3164
    at chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2:26090
    at chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2701:3164
    at xR
    at div
    at t (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2723:7303)
    at Ct (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2723:7751)
    at chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2:26090
    at chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2701:3164
    at p (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2304:4460)
    at fe (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2304:10712)
    at w (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2723:152)
    at D (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2723:914)
    at div
    at chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2:26090
    at chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2701:3164
    at chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2358:25477
    at Ra (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/main.js:17:15965)
    at Pa (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/main.js:17:18495)
    at _a (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/main.js:17:15785)
    at jR (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/502.js:2353:5501)
    at Suspense
    at no (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/502.js:741:824)
    at div
    at chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2:26090
    at chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2701:3164
    at Sx (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/502.js:259:2437)
    at $ (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2698:4754)
    at A (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2698:3156)
    at k (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2:26500)
    at O (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2698:534)
    at Z (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2698:5234)
    at chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2698:5669
    at $5 (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/main.js:52:36646)
    at pt (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2337:6272)
    at O8 (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/502.js:667:114)
    at P (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:124:91496)
    at D (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:124:91931)
    at I (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:124:92152)
    at De (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2737:5980)
    at j (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/502.js:2365:2274)
    at AR (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/502.js:2365:574)
    at xe (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2304:10081)
    at N (chrome-extension://gdokollfhmnbfckbobkdbakhilldkhcj/385.js:2295:3690)
      
```

To repeat, attempt to send ALF - type 0. - as soon as you type another character it crashes.
![image](https://github.com/alephium/extension-wallet/assets/20622085/8ed1c589-3a5b-4073-9e83-c452c7c68a52)

![image](https://github.com/alephium/extension-wallet/assets/20622085/f75c7b56-24bc-468c-a4b4-e27fa6f65ecd)

(note if you need ALF, ask cgi-bin)

**Comment by diomark** [comment]
Note Ryannn repeated the same test with the same results.
![image](https://github.com/alephium/extension-wallet/assets/20622085/ea162e49-ac14-49cd-9602-0b3c920ed3aa)

**Comment by diomark** [comment]
@nop33 let me know if you need an ALF for testing (If cgi-bin can't send)

**Comment by polarker** [comment]
@h0ngcha0 Please help us investigate and fix this

**Comment by h0ngcha0** [comment]
On it :+1:
